import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import StoreProvider from "@/lib/store/store-provider/StoreProvider";
import TransitionProvider from "@/Providers/transition.Provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const bebasNeue = localFont({
  src: "./fonts/BebasNeue-Regular.ttf",
  variable: "--font-bebas",
});

const jersey10 = localFont({
  src: "./fonts/Jersey10-Regular.ttf",
  variable: "--font-jersey",
});

const googleSans = localFont({
  src: [
    {
      path: "./fonts/GoogleSans-VariableFont_GRAD,opsz,wght.ttf",
      weight: "100 900",
      style: "normal",
    },
    {
      path: "./fonts/GoogleSans-Italic-VariableFont_GRAD,opsz,wght.ttf",
      weight: "100 900",
      style: "italic",
    },
  ],
  variable: "--font-google-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${bebasNeue.variable} ${jersey10.variable} ${googleSans.variable}  antialiased  `}
    >
      <body className="bg-black m-0">
        <TransitionProvider>
          <StoreProvider>
            {children}
          </StoreProvider>
        </TransitionProvider>
      </body>
    </html>
  );
}
